### ISSUE TITLE
Create a Social Preview

### ISSUE THREAD

**Issue by NathanielJS1541** [NathanielJS1541/pebble_protectors#25]
The "Social Preview" is an image that gets displayed when links to the repo are pasted into social apps. This is usually the logo for the project.

Here are the guidelines for the social preview:
> Upload an image to customize your repository’s social media preview.
> 
> Images should be at least 640×320px (1280×640px for best display).

And here is the example image:
![repository-open-graph-template](https://github.com/NathanielJS1541/pebble_protectors/assets/33491104/1a5fff25-f74e-41b3-8cd8-6cfc422ea159)

**Comment by dominicmason555** [comment]
![pebble](https://github.com/NathanielJS1541/pebble_protectors/assets/3105036/ae965beb-188d-4cea-842c-94952a6bedfb)

**Comment by NathanielJS1541** [comment]
Image is now in `main` and has been set as the social preview.
